### ISSUE TITLE
As soon as I enable any of these, white seems to get clipped and I cant restore it

### ISSUE THREAD

**Issue by patroza** [prod80/prod80-ReShade-Repository#3]
Im trying to use especially 03 Curved Levels to lower black floor in HDR problematic games like Callisto Protocl, and have a slight curve at the bottom while still tracking the rest of the pq curve, but really when I enable any of the prod80 presets in callisto protocol, bright areas get clipped, blue light in smoke becomes pure white, and no setting seems to affect it.

hard to capture, but tried, first is enabled (colors muted/turned white/clipped), second disabled;
![6B57DFA4-ED18-4D8D-9DE5-A71E6CDF8618](https://user-images.githubusercontent.com/42661/208774486-0e47d88d-a6b1-407b-bf53-c7158d13ba23.jpeg)
![1B784EDF-43F7-4BC5-AAFD-235358B77B9A](https://user-images.githubusercontent.com/42661/208774499-d188f56c-0624-47e7-adeb-e82b68dde115.jpeg)

**Comment by prod80** [comment]
This effect isn't made for HDR but LDR. Change to normal color depth (8 bit, not 10 bit HDR) and it should work fine.

**Comment by patroza** [comment]
@prod80 ah i see, thanks a lot for clarification!
Would you consider a hdr version?
